<a href="https://colab.research.google.com/github/Kasi-redddy/00_pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
print("Hello im exicted to learn Pytorch")

Hello im exicted to learn Pytorch


In [61]:
!sudo apt update
!sudo apt install nvidia-driver-<version-number>


Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
51 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InR

In [62]:
!pip install torch


In [63]:
import torch


In [64]:
torch.__version__

'2.5.0+cu121'

In [65]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


In [66]:
!nvidia-smi

Sat Nov  9 09:32:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Introduction to tensors
Creating tensore


In [67]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [68]:
scaler.ndim

0

In [69]:
scaler.item()

7

In [70]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [71]:
vector.ndim

1

In [72]:
vector.shape

torch.Size([2])

In [73]:
Matrix = torch.tensor([[7,8],
                      [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [74]:
Matrix.ndim

2

In [75]:
Matrix[1]

tensor([ 9, 10])

In [76]:
Matrix.shape

torch.Size([2, 2])

In [77]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [78]:
TENSOR.ndim

3

In [79]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [80]:
TENSOR.shape

torch.Size([1, 3, 3])

Random tensors.
why random tensors?

Random tensors are important because the way NN learns is that they start with tensors full of random those random numbers to be better represent data.

start with random numbers ->llok at data ->update random numbers ->look at data -> update

In [81]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7351, 0.7267, 0.1935, 0.1703],
        [0.5518, 0.2315, 0.6882, 0.3665],
        [0.8470, 0.8405, 0.6183, 0.8592]])

In [82]:
random_tensor.ndim

2

In [83]:
random_tensor.shape

torch.Size([3, 4])

In [84]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [85]:
# create a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [87]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
ones.dtype

torch.float32

In [89]:
random_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like

In [90]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
torch.__version__

'2.5.0+cu121'

In [92]:
# Use torch .range()
one_to_ten = torch.arange(start = 1, end = 11, step =1 )
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
#creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 90],
                               dtype = None,# What datatypes is the tensor(eg. Float 32 or float16
                               device=None,# What device is your tensor on
                               requires_grad=False) # weather or not to track gradient with this tempor operations

float_32_tensor

tensor([ 3.,  6., 90.])

In [95]:
float_32_tensor.dtype

torch.float32

In [96]:
floar_16_tensor = float_32_tensor.type(torch.float16)
floar_16_tensor

tensor([ 3.,  6., 90.], dtype=torch.float16)

In [97]:
floar_16_tensor*float_32_tensor

tensor([   9.,   36., 8100.])

In [98]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [99]:
float_32_tensor * int_32_tensor

tensor([  9.,  36., 810.])

**getting informatiom from tensors(Attributes)**

1.Tensors not right datatype- to do get datatype from a tensor, can use "tensor.dtype"
2. Tensors not right shape- to get shape from a tensor, can use "tensor.shape".
3. Tensors nor right device - to get device from a tensor, can use "tensor.device"

In [100]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0914, 0.3340, 0.5975, 0.9318],
        [0.4011, 0.2619, 0.7597, 0.3672],
        [0.4044, 0.5916, 0.0047, 0.7371]])

In [101]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0914, 0.3340, 0.5975, 0.9318],
        [0.4011, 0.2619, 0.7597, 0.3672],
        [0.4044, 0.5916, 0.0047, 0.7371]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# manipulating Tensors(tensor operations)
Tensors operations include:
    
    .Addition
    .Subtraction
    .Multiplication(element-wise)
    .Division
    .Matrix Multiplication


In [102]:
#Creating a tensor and Add 10 to it
tensor = torch.tensor([1 ,2 ,3])
tensor + 10

tensor([11, 12, 13])

In [103]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [104]:
tensor      # The tensor remains same from the starting and when we change the sign then only it will change

tensor([1, 2, 3])

In [105]:
# subtracting by 10
tensor - 10

tensor([-9, -8, -7])

In [106]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [107]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Elements-wise multiplication
2. Matrix Multiplication(dot product)


In [108]:
# Elements-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [109]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [110]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [111]:
%%time
value = 0
for i in range(len(tensor)):
  value +=tensor[i] * tensor[i]
print (value)

tensor(14)
CPU times: user 2.04 ms, sys: 0 ns, total: 2.04 ms
Wall time: 2.61 ms


In [112]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 29 µs, sys: 4 µs, total: 33 µs
Wall time: 36.7 µs


tensor(14)

# Threre are two main rules that performing matrix multiplication need to stisfy:
1. The ** Inner dimensions** must match:

 1.1 (3,2)@ (3,2) wont't work

 1.2   (2,3)@(3,2) will work

 1.3  (3,2)@(2,3) will work  

2. The resulting matrix has the shape of the **outer dimesions**:

   (2,3) @ (3,2) ->(2, 2)

   (3,2) @ (2,3) ->(3,3)
   


In [113]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0757, 0.8679],
        [0.6007, 0.4896]])

In [114]:
torch.matmul(torch.rand(2,3), torch.rand(2,3)) # because of first law it wont work

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [115]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3242, 0.6519, 0.6783],
        [0.4502, 0.3677, 0.3408],
        [0.3416, 0.5069, 0.5135]])

In [116]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[2.1679, 1.7998, 1.7402, 2.4692, 1.9717, 2.2994, 2.3427, 2.0299, 2.5262,
         2.3750],
        [2.3833, 2.2723, 1.9312, 1.5119, 2.0821, 2.1530, 2.0064, 1.6197, 2.8418,
         2.8261],
        [3.1230, 2.5694, 2.5668, 2.6029, 2.8454, 3.0500, 2.4094, 2.2110, 3.5837,
         3.2315],
        [1.6321, 1.5864, 1.3593, 1.2726, 1.6208, 1.5641, 1.7976, 1.1758, 1.9843,
         1.9376],
        [2.2407, 1.6718, 1.8345, 1.9348, 1.7689, 1.7198, 2.4592, 1.5883, 2.3770,
         2.6864],
        [2.2394, 2.0087, 1.8127, 1.7972, 2.2502, 2.7916, 1.5634, 1.5813, 2.6660,
         2.4236],
        [2.1260, 2.2245, 1.9082, 2.1793, 2.2739, 2.2638, 2.2963, 2.0246, 2.8985,
         2.6391],
        [2.4019, 1.8998, 1.9504, 2.7137, 2.8134, 3.1997, 2.8177, 2.4964, 2.3479,
         2.8996],
        [1.8667, 1.9948, 1.5749, 2.4502, 2.2356, 2.9114, 2.6185, 1.8226, 2.8695,
         2.7261],
        [2.3298, 1.3047, 1.9758, 2.6479, 2.1430, 2.0416, 2.4857, 2.2130, 2.2599,
         2.3933]])

In [117]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

# One of the most common errors in the deep learning: Shape errors

In [118]:
#shapes for matrix multiplicatio
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm(tensor_A, tensor_b) it is same as matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [119]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor sahpe issues, we can manipulate the shape of one of our tensors using **Transpose**.

A **Transpose** switches the axes or dimensions of given tensor

In [120]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [121]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [122]:
torch.matmul(tensor_A, tensor_B.T)   # Transpose

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [123]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [124]:
# all the code here with tensor_B is transposed
print(f"Orginal shapes: tensor_A ={tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f" New shapes: tensor_A ={tensor_A.shape}(same as the above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying:{ tensor_A.shape} @ {tensor_B.T.shape} <-inner dimessions must match" )
print("output:\n")
output  = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Orginal shapes: tensor_A =torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
 New shapes: tensor_A =torch.Size([3, 2])(same as the above), tensor_B = torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <-inner dimessions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


In [125]:
# There is an website called matrix multiplication which helps to check this maniually

#
Finding the min, max, mean, sum, etc (aggregation)

In [126]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [127]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [128]:
#find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [130]:
# Find the mean --NOte : the torch.mean() function requires a tensor of float32 datatypes to eork
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [129]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the positional min and max

In [131]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [132]:
# Find the postition in tensor that has the minimum value with argmin().
x.argmin()

tensor(0)

In [133]:
x[0]

tensor(1)

In [134]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [135]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsequeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* view - return  a view of an input tensor of certain shape but keep the same memeory
* Stacking - combine multiple tensors on the top of each other (vstack) or side by side(hstack)
* squeeze - remove all 1 dimensions from a tensor
* unsqueeze - add a 1 dimension to a target tensor
* permute - Return a view of input with dimensionx permuted(swapped) in certain way

In [136]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [137]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [138]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [139]:
# Chamging z changes x (because a view of a tensor shares the same memory as orginal)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [140]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [141]:
# torch.Squeeze()-removes all single dimesions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [142]:
x_reshaped.shape

torch.Size([1, 9])

In [143]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [144]:
# torch.Squeeze()-removes all single dimesions from a target tensor:: same as before but doing long code
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed =  x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [145]:
# torch.unsqueeze()- adds a single dimension to a target tensor at specifiv dim(dimension)
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

# add an extra dimension with sequeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [146]:
import torch

# Define the original tensor with the correct name
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

# Print shapes to confirm
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [147]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

# Indexing(selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy.

In [148]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
# Let's index on the middele bracket (dim =1)
x[0][0]

tensor([1, 2, 3])

In [151]:
#Let,s index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [152]:
x [0][2][2]

tensor(9)

In [153]:
# if you use ":" to select "all" of a target dimension\
x[:, 0]

tensor([[1, 2, 3]])

In [154]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [155]:
# Get all values of 0th and 1st dimension but only the 1 index value of 1 of 2nd dimension
x[:, 1, 1]

tensor([5])

In [156]:
# Get all values of 0th of 1st dimension and all values of  2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [157]:
# Index on x to return 9
print(x[0][2][2])
# Index on x to return 3, 6,9
print(x[:,:, 2])


tensor(9)
tensor([[3, 6, 9]])


# PyTorch tensors & NumPy

Numpy is a most popular scientific python numerical computing library.

and because of this, pytorch has functionality to interact with it..

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray).

* pytorch tensor -> NumPy-> torch.Tensor.numpy().


In [158]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [159]:
array.dtype

dtype('float64')

In [160]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [161]:
# cahnge the value of array, what will happen to do 'tensor'?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [162]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [166]:
numpy_tensor.dtype

dtype('float32')

In [168]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how Neural Network learns:

`start with random numbers -> tensor operations ->update random numbers to try and make them better representation of the data  -> again -> again -> again..`

To reduce the randomness in neural network and pytorch comes the concept of a  ** Random seed **.

Essentially what the random seed is "flavour" the  randomness




In [169]:
torch.rand(3 ,3)  # it will give random numbers when we run ..

tensor([[0.8992, 0.4134, 0.5280],
        [0.0137, 0.7021, 0.0035],
        [0.9233, 0.7866, 0.3028]])

In [170]:
import torch

#create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6154, 0.8664, 0.0898, 0.4470],
        [0.5294, 0.6365, 0.4767, 0.0882],
        [0.5794, 0.8700, 0.1094, 0.1904]])
tensor([[0.1713, 0.5731, 0.7482, 0.2052],
        [0.4903, 0.9183, 0.8014, 0.4385],
        [0.0925, 0.4237, 0.9190, 0.7311]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [171]:
# lets make some random but reproduciblity
import torch

# set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 1.Running tensors and PyTorch objects on the GPU's(and making faster computtions)

GPUs = Faster computation on numbers , thaks to CUDA + NVIDIA +PyTorch working behind the schene ro make evertthing good

In [172]:
!nvidia-smi

Sat Nov  9 09:36:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2.Check for GPU access with pytorch



In [173]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()    #cuda is nvidia progamming interface

True

In [174]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [175]:
# count devices
torch.cuda.device_count()

1

###3.Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.



In [176]:
#create a tensor (default on the cpu )

tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [177]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to the CPU




In [178]:
# If tensor is on GPU , can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [179]:
# to fix GPU tensor with NumPy issue , we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [180]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')